INSERT INTO `Round2` (`id`, `question`,`op1`, `op2`, `op3`, `op4`) VALUES
(1,'Ultra sonic waves are________','longitudinal  ','progressive  ','transverse  ','inverse'),
(2,'According to the newton''s formula the velocity of sound in air is_______','280m/s  ','332m/s  ','331.6m/s  ','350m/s'),
(3,'Hooke''s law essentially defines________','stress  ','strain  ','yield point  ','elastic limit'),
(4,'The poisson''s ratio can not have the value________','0.7  ','0.2  ','0.49  ','0.1'),
(5,'Individual Ownership is called as  ?','Joint trade business	',' sole proprietorship	',' co-operative society   ','partnership'),
(6,'Who takes no active part in Business  ?','CEO	',' managing director	','© Dormant Partner	','minor partner'),
(7,' Whose property is not liable for the debts of a company  ?','.Owner	',' shareholder		',' employee	',' minor partner'),
(8,'which word is the odd man out?',' Trivial	',' Unimportant		','Important		',' Insignificant'),
(9,' Antonym for AID','Help 		',' Hinder		',' Assist			',' Residnet'),
(10,' Window is to pane as book is to ________',' Novel	',' Glass','© Cover	',' Page'),
(11,' Optimist is to cheerful as pessimist is to ________',' Gloomy	',' Mean		',' Petty			',' Helpful'),
(12,' Select correct word:',' Guarrantee		',' Guarante		',' Gurantee		',' Guarantee'),
(13,'Which American computer company is called Big Blue?',' Tandy Svenson              ',' IBM    ',' Compaq Corpn              ',' Microsoft Corpn'),
(14,' The digital computer was developed primarily in',' UK             ',' USA                  ',' USSR                     ',' Japan'),
(15,' The first programming language was',' PASCAL',' FORTRAN ','COBOL','lisp'),
(16,' The input unit of a computer',' Directs all other units            ',' Feeds data to the CPU or memory',' Retrieves data from CPU         ',' Al l of the above'),
(17,'UNIVAC is','Universal Automatic Computer       ','Universal Array Computer','Unique Automatic computer           ',' Unvalued  Automatic Computer '),
(18,'Liability of a Company Secretary is–',' Contractual only     ',' Statutory only    ',' Civil only     ',' Both contractual and statutory'),
(19,'The primary function of an office is–'    ,' Making, using and preserving records		',' Remunerating personnel',' Carrying out management policies 		',' Safeguarding organization’s assets'),
(20,'In an office, Franking machine is used for–',' Punching card 					',' Accounting work',' Duplicating 					',' Postal stamp fixing'),
(21,' Fax is used for–',' Sending telephonic message 		 ',' Sending copies of documents',' Exercising control				 ',' Decision making'),
(22,' Keyboard of a computer is–',' An input device 				',' An output device',' A processing device 			',' A storage device'),
(23,' The polynomial x3+2x+3 has','.one negative and two real roots		','.three real roots ','.one positive and two imaginary roots		','.no solution '),
(24,' If sin-1x-cot-1(,1/2),=π/2,then x is equal to ','.1/2 	    ','.1/√5	    ','.2/√5     ','. √3/2'),
(25,' Temporary finger like extensions on amoeba are called','  Cell membrane			 ','  Cell wall','   Pseudopodia			 ','     Cilia'),
(26,' Blood consist of what fluid medium?','   Lymph			 ','   Plasma		 ','   All of these		 ','  Platelets'),
(27,'chemical name of washing soda is_________','sodium   carbonate 		  ','sodium chloride    ','sodium hydrogen carbonate	  ',' sodium hydroxide'),
(28,' nucleotides have how many components?',' 2		',' 3		',' 5		',' 4'),
(29,' How many districts of Tamil Nadu share the coastline?','10		','12		','13		',' 14'),
(30,'Tamil Nadu does not share its border with which of the following states?','AndhraPradesh	','Telangana	','Karnataka	',' Kerala');



